# Generated by Django 3.2.9 on 2021-11-28 15:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.project')),
                ('description', models.CharField(max_length=500)),
                ('job_type', models.CharField(max_length=50)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_type', models.CharField(max_length=50)),
                ('thumbnail', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=50)),
            ],

        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
