# Generated by Django 3.2.5 on 2024-01-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_hours_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='products.project'),
        ),
    ]
