# Generated by Django 3.2.5 on 2024-01-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.project'),
        ),
    ]
